pipeline {
    agent any
    environment {
        S3_DEV_BUCKET = 's3-dev'
        S3_PROD_BUCKET = 's3-prod'
    }
    parameters {
        choice(name: 'BRANCH_NAME', choices: ['develop', 'master'], description: 'Select the branch to deploy')
    }
    stages {
        stage('Upload to S3 - Dev') {
            when { 
                expression { return params.BRANCH_NAME == 'develop' } 
            }
            steps {
                sh '''
                    echo "Copying files to Development S3 bucket: $S3_DEV_BUCKET"
                    aws s3 cp . s3://$S3_DEV_BUCKET/ --recursive
                '''
            }
        }
        stage('Upload to S3 - Prod') {
            when { 
                expression { return params.BRANCH_NAME == 'master' } 
            }
            steps {
                sh '''
                    echo "Copying files to Production S3 bucket: $S3_PROD_BUCKET"
                    aws s3 cp . s3://$S3_PROD_BUCKET/ --recursive
                '''
            }
        }
    }
}
